{% set version = "0.6.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aws.signature
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/aws.signature_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/aws.signature/aws.signature_{{ version }}.tar.gz
  sha256: f7fe4f686979be21e5a8ba7ae11f0fade4f5aaf4e98063b5349ee0962dbb9496

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-digest
  run:
    - r-base
    - r-base64enc
    - r-digest

test:
  commands:
    - $R -e "library('aws.signature')"           # [not win]
    - "\"%R%\" -e \"library('aws.signature')\""  # [win]

about:
  home: https://github.com/cloudyr/aws.signature
  license: GPL-2.0-or-later
  summary: Generates version 2 and version 4 request signatures for Amazon Web Services ('AWS') <https://aws.amazon.com/> Application Programming Interfaces ('APIs') and provides a mechanism for retrieving credentials from environment variables, 'AWS' credentials files, and 'EC2' instance metadata. For use on 'EC2' instances,
    users will need to install the suggested package 'aws.ec2metadata' <https://cran.r-project.org/package=aws.ec2metadata>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: aws.signature
# Type: Package
# Title: Amazon Web Services Request Signatures
# Version: 0.5.2
# Date: 2019-08-08
# Authors@R: c(person("Thomas J.", "Leeper", role = c("aut"), email = "thosjleeper@gmail.com", comment = c(ORCID = "0000-0003-4097-6326")), person("Jonathan", "Stott", email = "jonathan.stott@magairports.com", role = c("cre", "aut")) )
# Description: Generates version 2 and version 4 request signatures for Amazon Web Services ('AWS') <https://aws.amazon.com/> Application Programming Interfaces ('APIs') and provides a mechanism for retrieving credentials from environment variables, 'AWS' credentials files, and 'EC2' instance metadata. For use on 'EC2' instances, users will need to install the suggested package 'aws.ec2metadata' <https://cran.r-project.org/package=aws.ec2metadata>.
# License: GPL (>= 2)
# Imports: digest, base64enc
# Suggests: testthat (>= 2.1.0), aws.ec2metadata (>= 0.1.6)
# URL: https://github.com/cloudyr/aws.signature
# BugReports: https://github.com/cloudyr/aws.signature/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-08 15:43:47 UTC; jon_m
# Author: Thomas J. Leeper [aut] (<https://orcid.org/0000-0003-4097-6326>), Jonathan Stott [cre, aut]
# Maintainer: Jonathan Stott <jonathan.stott@magairports.com>
# Repository: CRAN
# Date/Publication: 2019-08-08 16:10:02 UTC
