appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: R+tiXL4mQudclVc6yUKkeEKvRvTrgos+j1YAJ8qUS8Rci9RxnkMUn5IM/mmD3YNxjvoyKUInqVH2gmsRpyganaSWZk9hRN+IxsKfXNr+1OwJHK0GEwIYyEXGmeW1jMGzsfXaM7JMAKFxFiA19K6IcUvkzIM/fD04TWwop4pPhASCaCn+ofLMIEkxv8WKrIJKeoc+LFS2ODOQd2L+fCSf7zB9prWCBHd2FAZpfoRHUAsDA2yJpTutqBh3dqGWIz+4Y9uaQ76FvATGq34+qguxFutfojPDcdD3mIB7NkFkrsJy1zSnd/8KkVo/la9XJ6tnkDL9yiFamlGNF5k6YiYPBHIQc7yVn9AC3tkFF8P0nVXRoc4x6gCQ4CfxNuunyQHGmkDacwzJk1rOhbprMhLiZKX7honpSYPi5PD8d/b4bFoqHWvGF8mXjctY/xcresh8AVDl4n6dgNvi85fpFyh3BKWRKmpZmgtI5903g36+vNGdOkG+AIkI59WJK9o5wvsD3ZMR5IekqpUJ+RjMd1TVkTBjpheXqVdPazPlJcz7Wdx/OxmF1jLFRbR8153okIasWwm3Q/+lDTOr2qpdbETygLMNSRsp43/hwxm4Nn6MHuEzKlA/1DFTKGwo++yxjHsvp0ykDBuBJnjR1L4fNPKNBsiVYv+sTm6KGpDNNh9rHzk=}
