travis:
  secure:
    BINSTAR_TOKEN: cZZ4nfcLtlpRU5nqdD5XRrrM2ebl0if5y4ZO0FQ/5MaNxPYwCEBGya1zvTknQeLxtXdhpZK7zk+CuMWJzRHbixCZ9Dd7bruMvRjs15NnWNFjLTZ4ui6hC/kX9vnEilgnjSSB8mj6m6b49niHFXmAYEWKR9qSpb8IApdAsu2aLaeXGxutd0WCJ5x8PNffIZzb3FZ1pafSXdc3uLZOCV+OrFPGUvzwXJytNfNmc/LKiasE7NnPBarKha90y9ZJ73RUsQ/0M+xwi1/kuQTyCl2eSLBnujWg0E4F051B+yoDkS1dS0H9TM3VFZRi1vd/kNZw3eYx3lA6npj7UZM3DPejE8bN9rK+hnFLSXIcPSF7RnG0FS4R8HopEi+GngcTMzQ8DbW618brnI8LDBIG6h+nXPRnDn7u4UNc8rAlhucrsAFTYlpTBLIWvYGmLZjQW9LChSLG6IOJ3aoWIQcuXYql5Rpy9XQzZoEKvwh3HSts9aDSeXOSWt8UzbhD2pek/zd2iHGOLb+kDvn7C+V5ElwSf8CAqsJo6QI3aeBRf9YLvS81RSKDiIXgC1uLW5F8GWL0tsHiKXHhVm6sf0h6BLyNMFbSf4qnQLgOgrtvDO6aPOtrMXlk62HmRsrOiwQgHFS5Iw1qMht+2mya5RPE/OWKubYThijuJ1duQwGZDkLi77s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
